"""Some Modification in the Use_rganization Table

Revision ID: 45ccbf492b19
Revises: 00d6e99ed09c
Create Date: 2026-06-04 00:39:50.402224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ccbf492b19'
down_revision: Union[str, Sequence[str], None] = '00d6e99ed09c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
