"""Modified the Asset Type Table

Revision ID: 60f7fa101c6e
Revises: 45ccbf492b19
Create Date: 2026-06-04 09:48:45.799068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60f7fa101c6e'
down_revision: Union[str, Sequence[str], None] = '45ccbf492b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_type', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'asset_type', 'organization', ['organization_id'], ['organization_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'asset_type', type_='foreignkey')
    op.drop_column('asset_type', 'organization_id')
    # ### end Alembic commands ###
