"""Creating all tables

Revision ID: 9ee10fa73216
Revises: 
Create Date: 2026-06-02 16:40:03.860920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee10fa73216'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_type',
    sa.Column('asset_type_id', sa.UUID(), nullable=False),
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('asset_type_id')
    )
    op.create_index(op.f('ix_asset_type_asset_type_id'), 'asset_type', ['asset_type_id'], unique=False)
    op.create_table('organization',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('organization_id'),
    sa.UniqueConstraint('organization_name')
    )
    op.create_index(op.f('ix_organization_organization_id'), 'organization', ['organization_id'], unique=False)
    op.create_table('permissions',
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('permission_name', sa.String(length=100), nullable=False),
    sa.Column('permisssion_description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('permission_id'),
    sa.UniqueConstraint('permission_name')
    )
    op.create_index(op.f('ix_permissions_permission_id'), 'permissions', ['permission_id'], unique=False)
    op.create_table('roles',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.Enum('SUPERADMIN', 'ORG_ADMIN', 'IT_ADMIN', 'EMPLOYEE', name='rolename'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_index(op.f('ix_roles_role_id'), 'roles', ['role_id'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('user_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.create_table('asset',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('asset_type_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('asset_code', sa.String(length=10), nullable=False),
    sa.Column('asset_description', sa.String(length=1000), nullable=True),
    sa.Column('asset_status', sa.Enum('AVAILABLE', 'ALLOCATED', 'UNDER_MAINTENANCE', 'RETIRED', name='assetstatus'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_type.asset_type_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.organization_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_index(op.f('ix_asset_asset_code'), 'asset', ['asset_code'], unique=False)
    op.create_index(op.f('ix_asset_asset_id'), 'asset', ['asset_id'], unique=False)
    op.create_table('role_permission',
    sa.Column('role_permission_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('role_permission_id')
    )
    op.create_index(op.f('ix_role_permission_role_permission_id'), 'role_permission', ['role_permission_id'], unique=False)
    op.create_table('ticket',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('asset_type_id', sa.UUID(), nullable=False),
    sa.Column('ticket_title', sa.String(length=255), nullable=False),
    sa.Column('ticket_description', sa.String(length=1000), nullable=True),
    sa.Column('ticket_status', sa.Enum('TODO', 'IN_PROGRESS', 'RESOLVED', name='ticketstatus'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_type.asset_type_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.organization_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_index(op.f('ix_ticket_ticket_id'), 'ticket', ['ticket_id'], unique=False)
    op.create_table('user_organization',
    sa.Column('user_organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.organization_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_organization_id')
    )
    op.create_table('user_permission',
    sa.Column('user_permission_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('is_granted', sa.Boolean(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.UUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoking_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], ),
    sa.ForeignKeyConstraint(['revoked_by'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_permission_id')
    )
    op.create_index(op.f('ix_user_permission_user_permission_id'), 'user_permission', ['user_permission_id'], unique=False)
    op.create_table('user_role',
    sa.Column('user_role_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_role_id')
    )
    op.create_index(op.f('ix_user_role_user_role_id'), 'user_role', ['user_role_id'], unique=False)
    op.create_table('asset_assignment',
    sa.Column('asset_assignment_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.asset_id'], ),
    sa.ForeignKeyConstraint(['assigned_by'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('asset_assignment_id')
    )
    op.create_index(op.f('ix_asset_assignment_asset_assignment_id'), 'asset_assignment', ['asset_assignment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_assignment_asset_assignment_id'), table_name='asset_assignment')
    op.drop_table('asset_assignment')
    op.drop_index(op.f('ix_user_role_user_role_id'), table_name='user_role')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_user_permission_user_permission_id'), table_name='user_permission')
    op.drop_table('user_permission')
    op.drop_table('user_organization')
    op.drop_index(op.f('ix_ticket_ticket_id'), table_name='ticket')
    op.drop_table('ticket')
    op.drop_index(op.f('ix_role_permission_role_permission_id'), table_name='role_permission')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_asset_asset_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_asset_code'), table_name='asset')
    op.drop_table('asset')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_roles_role_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_permission_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_organization_organization_id'), table_name='organization')
    op.drop_table('organization')
    op.drop_index(op.f('ix_asset_type_asset_type_id'), table_name='asset_type')
    op.drop_table('asset_type')
    # ### end Alembic commands ###
